services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo18
    volumes:
      - postgres-data:/var/lib/postgresql/data # Datos persistentes de Postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo18"]
      interval: 10s
      retries: 5

  odoo:
    image: odoo:18.0
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${ODOO_PORT:-8169}:${ODOO_PORT:-8169}"
    volumes:
      - ./addons:/mnt/extra-addons  # Monta la carpeta local 'addons'
      - ./odoo.conf:/etc/odoo/odoo.conf  # Permite modificar la configuración
      - odoo-data:/var/lib/odoo  # Datos persistentes de Odoo
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dayronpeeta@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: postgres  
    ports:
      - "${PGA_PORT:-8180}:${PGA_PORT:-80}" # Puerto para acceder a pgAdmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  odoo-data: